services:
  backend:
    image: feather-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/feather.db:/app/db/database.sqlite