name: Build TypeScript
on:
  push:
    branches:
      - main
    paths:
      - 'apps/landing/**'
      - 'apps/web/**'
      - 'packages/ui/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-ts:
    name: SonarQube Scan for TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (monorepo root)
        run: npm install
      - name: Build all apps and packages with Turborepo
        run: npm turbo run build --filter=apps/landing... --filter=apps/web... --filter=packages/ui...
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.sources=apps/landing,apps/web,packages/ui
            -Dsonar.exclusions=**/node_modules/**,**/dist/**