name: Build TypeScript
on:
  push:
    branches:
      - main
    paths:
      - 'apps/landing/**'
      - 'apps/web/**'
      - 'packages/ui/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-ts:
    name: SonarQube Scan for TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}